### ISSUE TITLE
submit scripts don't work well with older Python 2.7

### ISSUE THREAD

**Issue by zagrodzki** [MTG/sms-tools#37]
An attempt to submit a result to coursera (at least in A1, using submitA1.py) results in:

urllib2.URLError: <urlopen error [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>

or with requests:

requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

This is caused by lack of SNI (https://en.wikipedia.org/wiki/Server_Name_Indication) support in python ssl libraries up to and including python 2.7.8. SNI support is required for HTTPS access to www.coursera.org.

Python 2.7.9 has a backported ssl module from Python 3.4, I think it should work fine. For Python <2.7.9, as a workaround one can install packages "pyopenssl", "pyasn1" and "ndg-httpsclient". This is an alternative to built-in ssl/urllib package that will be used by "requests" if present.

It would be useful to check the Python version in submission scripts and print the warning about pyopenssl/pyasn1/ndg-httpsclient if SSL exception is raised from requests.post().

**Comment by xserra** [comment]
This is not an sms-tools problem, closing.

**Comment by tjs1297** [comment]
How did you solve this issue.?
